# Generated by Django 5.0.3 on 2024-04-29 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groupetontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cotisation_amount', models.CharField(max_length=150)),
                ('frequence_paiement', models.CharField(max_length=70)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=200)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('motdepasse', models.CharField(max_length=100)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('adresse', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.groupetontine')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.user')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_contribution', models.CharField(max_length=500)),
                ('date_contribution', models.DateTimeField(auto_now_add=True)),
                ('groupe_tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.groupetontine')),
                ('utilisateur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.user')),
            ],
        ),
    ]
